version: '3'

services:

  app-db_local:
    image: postgres:13
    environment:
      POSTGRES_DB: streamers
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: 12345
    volumes:
      - app-db-data:/var/lib/postgresql/data
    ports:
      - "5434:5432" # прослушивание порта 5434 на хосте и перенаправление на 5432 в контейнере
    networks:
      - my-network-local


volumes:
  app-db-data:
networks:
  my-network-local:
